server:
  port: 2333

lavalink:
  server:
    password: "youshallnotpass"
    sources:
      youtube: false
      soundcloud: true
      bandcamp: true
      twitch: true
      vimeo: true
      http: true
      local: false

logging:
  level:
    dev.lavalink.youtube.http.YoutubeOauth2Handler: INFO

plugins:
  youtube:
    enabled: true
    allowSearch: true
    allowDirectVideoIds: true
    allowDirectPlaylistIds: true
    clients:
      - MUSIC
      - WEB
      - ANDROID_VR
      - TVHTML5_SIMPLY
      - TV
    remoteCipher:
      url: "https://cipher.kikkia.dev/"
      userAgent: "bot-mus-dc"
    oauth:
      enabled: true
      refreshToken: "${YOUTUBE_REFRESH_TOKEN:}"
      skipInitialization: true
